# Caso practico: Neurona de McCulloch y Pitts

## 1. Implementacion de MPNeuron

In [1]:
import numpy as np

### Declaracion de la clase MPNeuron

In [3]:
class MPNeuron:
    def __init__(self):
        self.threshold = None

    def model(self,x):
        # input: [x1, x2, x3, .... ,xn] [1, 0 , 1, 1] (Binarios)
        z = sum(x)
        return z >= self.threshold

    def predic(self, X):
        # input: [[1 ,0 ,1, 0], [1, 0, 1, 1]] (Binarios)
        Y = []
        for x in X:
            result = self.model(x)
            Y.append(result)
        return np.array(Y)

### Instanciamos a la clase

In [4]:
mp_neurona = MPNeuron()

In [8]:
mp_neurona.threshold = 3

In [9]:
mp_neurona.predic([[1,1,0,0],[1,1,0,1],[1,0,0,0]])

array([False,  True, False])

### Implementando compuerta logica AND

In [10]:
mp_neurona.threshold = 2
mp_neurona.predic([[0,0,1,1],[0,1,0,1]])

array([ True,  True])

### Implementando compuerta logica OR

In [12]:
mp_neurona.threshold = 1
mp_neurona.predic([[0,0,1,1],[0,0,0,1]])

array([ True,  True])